# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UoaIbZtDq3b1KH6HBdxqRJLLYpdnM20p
"""

!pip install faiss-cpu
!pip install sentence-transformers

import pandas as pd
pd.set_option('display.max_colwidth', 100)

df = pd.read_csv("sample_text.csv")
df.shape

df

from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

vectors.shape

dim = vectors.shape[1]
dim

import faiss

index = faiss.IndexFlatL2(dim)

index.add(vectors)

index

search_query = "I want to buy a polo t-shirt"
vec = encoder.encode(search_query)
vec.shape

import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

distances, I = index.search(svec, k=2)
distances

I

I.tolist()

row_indices = I.tolist()[0]
row_indices

df.loc[row_indices]

search_query

